### PR TITLE
fix: FAQ mobile styling

### PR DESCRIPTION
**Pull request by jackyyzhang03**
### Tickets:

- HCK-

### List of changes:

- Changed some CSS for the FAQ for low-width screens so it looks like the design
- Previously background looked transparent on mobile and content would clip past container on certain widths

### Type of change:

- [X] Bug fix
- [ ] New feature
- [ ] Breaking change
- [ ] New release
- [ ] Requires a documentation update

### PR Checklist:

- [X] Merged `develop` branch (before testing)
- [ ] Ran `yarn format` to format code
- [ ] Listed change(s) in the Changelog
- [X] Tested all links in project relevant browsers
- [X] Tested all links on different screen sizes
- [ ] Referenced all useful info (issues, tasks, etc)

### CODE REVIEW

**Review by brarsanmol — COMMENTED** [review]
@logan-r mentioned adding the breakpoints to the style variables file to prevent the amount of magic number's in the source code in #6. Maybe we should start the process here and move forward?

See #7 for some of the work i've done cleaning up the variables file. Maybe we should attempt to merge that in this PR?

**Comment by jackyyzhang03** [comment]
> @logan-r mentioned adding the breakpoints to the style variables file to prevent the amount of magic number's in the source code in #6. Maybe we should start the process here and move forward?
> 
> See #7 for some of the work i've done cleaning up the variables file. Maybe we should attempt to merge that in this PR?

Sounds good, there are definitely a lot of magic numbers here. Though I am not entirely sure how to standardize these breakpoints since they are pretty specific to the FAQ. Maybe there is a better way to resize the container but I don't have a simple solution off the top of my head.

However, right now, the FAQ section looks pretty strange on mobile and this PR will at least solve that issue.

IMG_4246

**Comment by brarsanmol** [comment]
> > @logan-r mentioned adding the breakpoints to the style variables file to prevent the amount of magic number's in the source code in #6. Maybe we should start the process here and move forward?
> > See #7 for some of the work i've done cleaning up the variables file. Maybe we should attempt to merge that in this PR?
> 
> Sounds good, there are definitely a lot of magic numbers here. Though I am not entirely sure how to standardize these breakpoints since they are pretty specific to the FAQ. Maybe there is a better way to resize the container but I don't have a simple solution off the top of my head.
> 
> However, right now, the FAQ section looks pretty strange on mobile and this PR will at least solve that issue.
> 
> IMG_4246

Sounds good, I will approve the PR and let @logan-r decide where to go from here, over the next month I'll start work on that task.

**Review by brarsanmol — APPROVED** [review]
LGTM!

**Pull request merged**
